
#-----------------------------------------------
#Config that does not have impact on performance
#-----------------------------------------------


random_seed: 0b011011

#-----------------------------------------------
#1. Dataset
#-----------------------------------------------

dataset:

#directory that have every dataset in it.
  data_dir: /media/youngwon/Neo/NeoChoi/Dataset/noisy-vctk-16k-speechbrain

  # clean_train: "clean/train"
  clean_train: "clean_trainset_28spk_wav_16k"
  clean_val: "clean_testset_wav_16k"

  # noisy_train: "noisy/train"
  noisy_train: "noisy_trainset_28spk_wav_16k"
  noisy_val: "noisy_testset_wav_16k"

#So for this case, wideband test dataset should be located at "/media/zeroone/target/test"

  frame_size: 2048
  hop_size: 256

  batch_size: 256
  num_workers: 16
 
#-----------------------------------------------
#2. Model
#-----------------------------------------------

model:
  kernel_size: 11

#-----------------------------------------------
#3. Loss
#-----------------------------------------------
#for STFT Loss
loss:
  window_size: 512
  hop_size: 256

#-----------------------------------------------
#4. Optimizer(ADAM)
#-----------------------------------------------
optim:
  initial_lr: 0.0002

  B1: 0.5
  B2: 0.9

  lr_gamma: 1

#-----------------------------------------------
#Training
#-----------------------------------------------

train:
  total_epoch: 100

#Path of output of validation. 
  output_dir_path: "./output"
  logger_path: "./logger"

